//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PraxellMedia
    {
        public long repTransId { get; set; }
        public string serverData { get; set; }
        public Nullable<System.DateTime> serverTime { get; set; }
        public string TransactionDate { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public string Activity { get; set; }
        public Nullable<long> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<byte> decimalCurrency { get; set; }
        public string orderID { get; set; }
        public string cardNumber { get; set; }
        public Nullable<long> cardSerialNumber { get; set; }
        public string cardIssuerSN { get; set; }
        public Nullable<int> cardIssuerPNumber { get; set; }
        public string cardSeriesNumber { get; set; }
        public string cardBatchNumber { get; set; }
        public string actionNetworkID { get; set; }
        public string actionVendorPNumber { get; set; }
        public string actionStoreId { get; set; }
        public string actionStorePNumber { get; set; }
        public string actionCashierId { get; set; }
        public string actionTicketId { get; set; }
        public string actionType { get; set; }
        public string cardExpirationDate { get; set; }
        public string VoidTransactionServerDate { get; set; }
        public Nullable<System.DateTime> VoidTransactionServerTime { get; set; }
        public string VoidTransactionDate { get; set; }
        public Nullable<System.DateTime> VoidTransaction { get; set; }
        public Nullable<long> VoidTransactionID { get; set; }
        public string VoidTransactionOrderID { get; set; }
        public string VoidTransactionActionNetworkID { get; set; }
        public Nullable<int> VoidTransactionActionVendorPNumber { get; set; }
        public string VoidTransactionActionStoreId { get; set; }
        public string VoidTransactionActionStorePNumber { get; set; }
        public string VoidTransactionActionCashierId { get; set; }
        public string VoidTransactionActionTicketId { get; set; }
        public string VoidTransactionActionType { get; set; }
    }
}
