//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customers
    {
        public decimal id { get; set; }
        public Nullable<decimal> cust_id { get; set; }
        public string cust_name { get; set; }
        public decimal idd { get; set; }
        public Nullable<System.DateTime> ReservedTime { get; set; }
    }
}
